### Purpose: Test encoding pipeline for predictor data, encoding.py debugging not done yet

source_path: "data/preprocessed/predictor_preprocessed_20250609.csv"
target_path: "data/encoded/predictor_encoded_20250609.npy"