### Purpose: Added percentile conversion (first run with this function added in.) Otherwise same as 20250609.

# the parameters for filtering
filter_params:
  usage_frequency: 0.15
  usage_days: 60
  eps_days: 7
  min_samples: 10
# input data source
source:
  directory: "data/raw/"
  filename: "predictor_data_20250529.csv"
# output data source
target:
  directory: "data/preprocessed/"
  filename: "predictor_preprocessed_20250709.csv"