### Purpose: Added percentile conversion (second run with this function added in.) Otherwise same as 20250709.
# Changes made: added target columns to conver_to_percentile function as both should be percentile scores

# the parameters for filtering
filter_params:
  usage_frequency: 0.15
  usage_days: 60
  eps_days: 7
  min_samples: 10
# input data source
source:
  directory: "data/raw/"
  filename: "predictor_data_20250529.csv"
# output data source
target:
  directory: "data/preprocessed/"
  filename: "predictor_preprocessed_20250826.csv"