### Purpose: Using v1 final configuration.
### Shoulld be identical to 20250709, but with target also in percentile scores.
settings:
  device: "cpu"  # or "cpu"
  run_desc: "Second training run with percentile scores instead of raw domain scores"
  seed: 42
  test_ratio: 0.25
  val_ratio: 0.2 # 0.2 of training data after test split  = 0.75 * 0.2 = 0.15 of total data
data:
  source: "data/encoded/predictor_encoded_20250826.npy"
  destination_base: "outputs/training_runs/"
hyperparams:
  optimizer: "adam"
  loss_function: "mse"
  epochs: 1000
  batch_size: 10000
  n_samples: 100000
  learning_rate: 0.001
  dims: 42 # dimenions of the input data (shape[1], default to 42 for predictor)