# data source
source:
  type: database
  sql_file_path: sql/predictor_data_query_20250529.sql
  sql_params: config/connection/constant_therapy_config.json
# data destination
output:
  dest: data/raw/
  filename: predictor_data_20250529.csv